// Generated by CoffeeScript 1.3.1
(function() {
  var create, loadTasks, tasks_exist;

  $(function() {
    console.log("in todoapp");
    $("#tasks").sortable();
    return $("#todotext").keydown(function(e) {
      var code;
      code = e.keyCode;
      console.log("Code pressed: " + code);
      if (code === 13 || code === 10) {
        console.log('Enter key was pressed.');
      }
      return e.preventDefault();
    });
  });

  loadTasks = function() {
    var ids;
    ids = Object.keys(localStorage);
    console.log("ids", ids);
    if (!_.isEmpty(ids)) {
      return $("#taskList #title").show();
    }
  };

  tasks_exist = function() {
    var ids;
    ids = Object.keys(localStorage);
    if (!_.isEmpty(ids)) {
      return true;
    } else {
      return false;
    }
  };

  create = function() {};

}).call(this);
