// Generated by CoffeeScript 1.3.1
(function() {
  var create, loadTasks, tasksExist;

  $(function() {
    var textfield;
    console.log("in todoapp");
    $("#tasks").sortable();
    textfield = $("#todotext");
    return $("#todotext").keydown(function(e) {
      var code, taskText;
      code = e.keyCode;
      if (code === 13) {
        taskText = $("#todotext")[0].value;
        console.log('Enter key was pressed.');
        return console.log("Task: " + taskText);
      }
    });
  });

  create = function() {};

  loadTasks = function() {
    var ids;
    ids = Object.keys(localStorage);
    console.log("ids", ids);
    if (tasksExist()) {
      return $("#taskList #title").show();
    }
  };

  tasksExist = function() {
    var ids;
    ids = Object.keys(localStorage);
    if (!_.isEmpty(ids)) {
      return true;
    } else {
      return false;
    }
  };

}).call(this);
